# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbezerra', '0003_critica'),
    ]

    operations = [
        migrations.AddField(
            model_name='critica',
            name='link',
            field=models.CharField(default='', max_length=50),
        ),
    ]
