# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jbezerra', '0004_critica_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='critica',
            old_name='link',
            new_name='link_critico',
        ),
    ]
