# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbezerra', '0005_auto_20170211_0415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='critica',
            old_name='ordem_critico',
            new_name='exibe_critico',
        ),
        migrations.AddField(
            model_name='critica',
            name='exibe_menu',
            field=models.BooleanField(default=0),
        ),
    ]
