# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbezerra', '0006_auto_20170211_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critica',
            name='exibe_menu',
            field=models.IntegerField(default=0),
        ),
    ]
